[project]
name = "tenpodeployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "numpy>=2.3.0",
    "python-json-logger>=3.3.0",
    "torch>=2.7.1",
]
