name: deploy-to-gcp-with-terraform

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:


jobs:
  deploy-to-cloud-run:
    #needs: build-and-push
    runs-on: ubuntu-latest
    environment: develop

    env:
      TF_VAR_project_id: ${{ vars.project_id }}
      TF_VAR_region: ${{ vars.region }}
      TF_VAR_service_name: ${{ vars.service_name }}
      TF_VAR_image_url: ${{ vars.image_url }}
      TF_VAR_cloud_run_sa_email: ${{ vars.cloud_run_sa_email }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}  

    steps:
      - name: Checkout Terraform code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./cloudrun-terraform

      - name: Terraform Apply
        env: 
          TF_LOG: DEBUG
        run: terraform apply -auto-approve
        working-directory: ./cloudrun-terraform